Subo ejercicio de Registro Automotor
elojodenestor/cfl2020 pull request #7
Opened 2020-07-27 21:00 UTC by elojodenestor

2020-07-30 13:40 UTC, rbeltracchi requested changes
estas subiendo de nuevo muchos ejercicios viejos. Esos no deberian estar en master ya? Acordate de hacer pull en tu master local despues de cada merge y antes de sacar un nuevo branch.

Ya hilando un poco mas fino, si usas variables/metodos en ingles, no mezcles entre ingles y español, trata de ser constante con esas decisiones.

2020-07-30 13:40 UTC, rbeltracchi commented on POO/Clase21_Mie0807/.gitignore
> +node_modules/
podes unificar, no necesitas un gitignore por cada carpeta. en el gitignore de la raiz del proyecto escribilo asi `*node_modules/`

2020-07-30 13:40 UTC, rbeltracchi commented on POO/Clase21_Mie0807/ejercicio-auto/auto.ts
> +        let p : string = arrayAutito[0];
nombres representativos!

2020-08-04 00:33 UTC, elojodenestor commented on POO/Clase21_Mie0807/.gitignore
> +node_modules/
Perfecto, anotado, Rodrigo! Gracias!

2020-08-04 00:39 UTC, merged